//#include "BinaryReader.h"
//#include "BrandData.h"
//#include "BrandListConfig.h"
//#include "DateTime.h"
//#include "Global.h"
//#include "SystemExcutor.h"
//#include "PriceData.h"
//#include "splitreplace.h"
//#include "StreamReader.h"
//#include "zengoopen.h"
//#include "PricePairList.h"
//#include "LogData.h"
//#include "Performance.h"
//#include "formatNumber.h"
#include "DataWriter.h"


